api_credentials:
    filename: creds.json

google_sheets:
    seniors_update_doc_name: Befriending List Updates
    befriending_seniors_update_sheet_name: befriending
    frail_seniors_update_sheet_name: frail

# Reminding volunteers to update seniors' status post volunteering session
# Default: sat 12 00
post_volunteering_update_message_scheduler:
    day_of_week : sat
    hour : 12
    minute : 00

# Update at end of day on which seniors' status have not been updated
# Default: sat 20 00
post_volunteering_reminder_to_update_status_scheduler:
    day_of_week : sat
    hour : 20
    minute : 00

# Creates weekly poll for volunteers to vote if they are coming
# Default: tue 18 00
create_weekly_poll_message_scheduler:
    day_of_week : tue
    hour : 18
    minute : 00

# Stops the poll from above
# Default: fri 20 00
stop_weekly_poll_message_scheduler:
    day_of_week : fri
    hour : 20
    minute : 00

send_report_to_vm_group_scheduler:
    day_of_week : sun
    hour : 00
    minute : 15
send_report_to_vm_group_scheduler_2:
    day_of_week : sun
    hour : 12
    minute : 15

generate_report_from_template_settings:
    # Weekly Report Template Document Name (without Directory)
    template_path: template.docx
    # Weekly Report Template File Directory (separate each sub folder with /)
    report_folder: reports

